### ISSUE TITLE
After ~20 searches Findr is broken

### ISSUE THREAD

**Issue by surcoufx83** [surcoufx83/sysHUB-Findr#5]
Du to storage limitations Findr stops working after a number of searches. The browser shows an exception:

```
ERROR DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '1707395.322' exceeded the quota.
    at CacheService.setResult (https://localhost:4200/main.js:6576:20)
    at SearchService.searchstep2_loop (https://localhost:4200/main.js:8200:18)
    at https://localhost:4200/main.js:8207:12
    at timer (https://localhost:4200/polyfills.js:10234:27)
    at _ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:8289:171)
    at https://localhost:4200/vendor.js:60699:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (https://localhost:4200/vendor.js:60699:30)
    at _ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:8289:54)
    at Object.onInvokeTask (https://localhost:4200/vendor.js:61013:25)
    at _ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:8289:54)
```

**Comment by surcoufx83** [comment]
This is caused by the limitations of the localstorage and sessionstorage in the browser. I guess it will also cause trouble for very huge syshub environments with lots of workflows, pset and config. 
In the future we will move to IndexedDB which allows much more data in the browser storage.

**Comment by surcoufx83** [comment]
Temporary fix included in https://github.com/surcoufx83/sysHUB-Findr/commit/f48cf30936eb9617a3af73a21a8f24ed1d08679a

**Comment by surcoufx83** [comment]
Removed some entities from localStorage and search results are saved in a new object in localStorage instead of sessionStorage.
There should no issues occur anymore.
As IndexedDB is not easy to handle it will not be implemented for now.
